### ISSUE TITLE
vercel 部署失败

### ISSUE THREAD

**Issue by kwxmxb** [jarvis2f/vortex#10]
在部署过程中出现该报错，导致提示错误

`[10:16:10] Running build in Washington, D.C., USA (East) – iad1
[10:16:11] Cloning github.com/kwxmxb/vortexmb (Branch: main, Commit: 1b39bab)
[10:16:12] Previous build cache not available
[10:16:14] Cloning completed: 3.093s
[10:16:15] Running "vercel build"
[10:16:16] Vercel CLI 34.1.10
[10:16:17] Installing dependencies...
[10:16:41] npm WARN deprecated @walletconnect/mobile-registry@1.4.0: Deprecated in favor of dynamic registry available from: https://github.com/walletconnect/walletconnect-registry
[10:16:41] npm WARN deprecated safe-event-emitter@1.0.1: Renamed to @metamask/safe-event-emitter
[10:16:42] npm WARN deprecated @walletconnect/types@1.8.0: WalletConnect's v1 SDKs are now deprecated. Please upgrade to a v2 SDK. For details see: https://docs.walletconnect.com/
[10:16:45] npm WARN deprecated @walletconnect/client@1.8.0: WalletConnect's v1 SDKs are now deprecated. Please upgrade to a v2 SDK. For details see: https://docs.walletconnect.com/
[10:16:46] npm WARN deprecated @walletconnect/qrcode-modal@1.8.0: WalletConnect's v1 SDKs are now deprecated. Please upgrade to a v2 SDK. For details see: https://docs.walletconnect.com/
[10:17:07] 
[10:17:07] > vortex@0.1.2 postinstall
[10:17:07] > prisma generate
[10:17:07] 
[10:17:08] Prisma schema loaded from prisma/schema.prisma
[10:17:09] 
[10:17:09] ✔ Generated Prisma Client (v5.7.1) to ./node_modules/@prisma/client in 386ms
[10:17:09] 
[10:17:09] Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
[10:17:09] ```
[10:17:09] import { PrismaClient } from '@prisma/client'
[10:17:09] const prisma = new PrismaClient()
[10:17:09] ```
[10:17:09] or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
[10:17:09] ```
[10:17:09] import { PrismaClient } from '@prisma/client/edge'
[10:17:09] const prisma = new PrismaClient()
[10:17:09] ```
[10:17:09] 
[10:17:09] See other ways of importing Prisma Client: http://pris.ly/d/importing-client
[10:17:09] 
[10:17:09] ┌─────────────────────────────────────────────────────────────┐
[10:17:09] │  Deploying your app to serverless or edge functions?        │
[10:17:09] │  Try Prisma Accelerate for connection pooling and caching.  │
[10:17:09] │  https://pris.ly/cli/accelerate                             │
[10:17:09] └─────────────────────────────────────────────────────────────┘
[10:17:09] 
[10:17:09] 
[10:17:09] warn Versions of prisma@5.8.1 and @prisma/client@5.7.1 don't match.
[10:17:09] This might lead to unexpected behavior.
[10:17:09] Please make sure they have the same version.
[10:17:09] 
[10:17:09] > vortex@0.1.2 prepare
[10:17:09] > husky install
[10:17:09] 
[10:17:09] husky - Git hooks installed
[10:17:09] 
[10:17:09] added 1443 packages in 51s
[10:17:09] 
[10:17:09] 275 packages are looking for funding
[10:17:09]   run `npm fund` for details
[10:17:09] Detected Next.js version: 14.1.0
[10:17:09] Running "next build && prisma migrate deploy"
[10:17:09] ❌ Invalid environment variables: {
[10:17:09]   DATABASE_URL: [ 'Required' ],
[10:17:09]   NEXTAUTH_SECRET: [ 'Required' ],
[10:17:09]   EMAIL_SERVER: [ 'Required' ],
[10:17:09]   EMAIL_FROM: [ 'Required' ],
[10:17:09]   REDIS_URL: [ 'Required' ],
[10:17:09]   SERVER_URL: [ 'Required' ]
[10:17:09] }
[10:17:09]  ⨯ Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
[10:17:09] 
[10:17:09] > Build error occurred
[10:17:09] Error: Invalid environment variables
[10:17:09]     at m (file:///vercel/path0/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:585)
[10:17:09]     at f (file:///vercel/path0/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:775)
[10:17:09]     at P (file:///vercel/path0/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:1174)
[10:17:09]     at file:///vercel/path0/src/env.js:5:20
[10:17:09]     at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
[10:17:09]     at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
[10:17:09]     at async file:///vercel/path0/next.config.js:7:1
[10:17:09] Error: Command "next build && prisma migrate deploy" exited with 1
[10:17:10] `

**Comment by jarvis2f** [comment]
❌ Invalid environment variables: { [10:17:09]   DATABASE_URL: [ 'Required' ], [10:17:09]   NEXTAUTH_SECRET: [ 'Required' ], [10:17:09]   EMAIL_SERVER: [ 'Required' ], [10:17:09]   EMAIL_FROM: [ 'Required' ], [10:17:09]   REDIS_URL: [ 'Required' ], [10:17:09]   SERVER_URL: [ 'Required' ] [10:17:09] }
