### ISSUE TITLE
修改了NEXTAUTH_URL之后，邮箱登录处的输入框和发送按钮没了

### ISSUE THREAD

**Issue by startwish** [jarvis2f/vortex#4]
RT，修改了NEXTAUTH_URL之后，邮箱登录处的输入框和发送按钮没了，不修改NEXTAUTH_URL点发送后又会跳转到localhost:3000

**Comment by startwish** [comment]
![image](https://github.com/jarvis2f/vortex/assets/32985693/baf9c433-2c4c-4133-bbd4-4aaf143aaf77)

**Comment by jarvis2f** [comment]
vercel部署还是docker，有日志吗

**Comment by startwish** [comment]
> vercel部署还是docker，有日志吗

docker部署，日志里在up后没报错，但访问页面日志里会出一堆redis的错，和redis的用户名密码相关，但反复修改，确定conf文件和.env文件里的是对的上的，但还是报这个错。

日志里没有除redis报错以外的错误，但redis的错误不影响 输入框和按钮 的显示问题。

补充一下，我是把localhost:3000改成了IPv6地址加端口（比如，[2400::1]:18000）的形式，首页访问是没问题的，到了登录页就没有输入框和按钮。不清楚是不是这个的影响，暂时还没法验证。

下面是docker的容器logs

Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "vortex", schema "public" at "vortex-postgres:5432"

1 migration found in prisma/migrations

Applying migration `20240315073121_init`

The following migration(s) have been applied:

migrations/
  └─ 20240315073121_init/
    └─ migration.sql
      
All migrations have been successfully applied.
   ▲ Next.js 14.1.0
   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000

 ✓ Ready in 238ms
register instrumentation for nodejs
Initializing pino-prisma
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
Log retention level: 30
register instrumentation for edge
Initializing pino-prisma
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'auth', args: [ 'vortex-main', 'h1D4h5fyvgW9' ] }
}
ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'auth', args: [ 'vortex-main', 'h1D4h5fyvgW9' ] }
}
ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'auth', args: [ 'vortex-main', 'h1D4h5fyvgW9' ] }
}
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
Log retention level: 30
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)
[ioredis] Unhandled error event: o: WRONGPASS invalid username-password pair or user is disabled.
    at /app/.next/server/chunks/115.js:139:24247
    at b (/app/.next/server/chunks/115.js:139:24256)

**Comment by startwish** [comment]
Docker默认只支持IPv4，需要额外设置才能用IPv6。Redis报的错是密码搞错导致连不上。
