### ISSUE TITLE
docker部署不成功+1

### ISSUE THREAD

**Issue by akiker233** [jarvis2f/vortex#9]
日志如下：
```
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "vortex", schema "public" at "vortex-postgres:5432"

Error: P1000: Authentication failed against database server at `vortex-postgres`, the provided database credentials for `1234` are not valid.

Please make sure to provide valid database credentials for the database server at `vortex-postgres`.
   ▲ Next.js 14.1.0
   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000

 ✓ Ready in 696ms
register instrumentation for nodejs
Initializing pino-prisma
PrismaClientInitializationError: 
Invalid `prisma.config.findUnique()` invocation:


Authentication failed against database server at `vortex-postgres`, the provided database credentials for `1234` are not valid.

Please make sure to provide valid database credentials for the database server at `vortex-postgres`.
    at si.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:125:7117)
    at si.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:125:6151)
    at si.request (/app/node_modules/@prisma/client/runtime/library.js:125:5859)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:130:10025)
    at async pinoPrisma (file:///app/src/lib/pino-prisma.mjs:6:18)
    at async /app/node_modules/pino/lib/worker.js:15:20
    at async Promise.all (index 0)
    at async module.exports (/app/node_modules/pino/lib/worker.js:13:13)
    at async start (/app/node_modules/thread-stream/lib/worker.js:61:17)
PrismaClientInitializationError: 
Invalid `prisma.config.findUnique()` invocation:


Authentication failed against database server at `vortex-postgres`, the provided database credentials for `1234` are not valid.

Please make sure to provide valid database credentials for the database server at `vortex-postgres`.
    at si.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:125:7117)
    at si.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:125:6151)
    at si.request (/app/node_modules/@prisma/client/runtime/library.js:125:5859)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:130:10025)
    at async pinoPrisma (file:///app/src/lib/pino-prisma.mjs:6:18)
    at async /app/node_modules/pino/lib/worker.js:15:20
    at async Promise.all (index 0)
    at async module.exports (/app/node_modules/pino/lib/worker.js:13:13)
    at async start (/app/node_modules/thread-stream/lib/worker.js:61:17)
Error: the worker has exited
    at ThreadStream.write (/app/node_modules/thread-stream/index.js:235:19)
    at Pino.write (/app/node_modules/pino/lib/proto.js:217:10)
    at Pino.LOG (/app/node_modules/pino/lib/tools.js:62:21)
    at Pino.fatal (/app/node_modules/pino/lib/levels.js:26:16)
    at process.<anonymous> (/app/.next/server/chunks/7613.js:41:4216)
    at process.emit (node:events:530:35)
    at process._fatalException (node:internal/process/execution:178:25)
prisma:error 
Invalid `prisma.agent.findMany()` invocation:


Authentication failed against database server at `vortex-postgres`, the provided database credentials for `1234` are not valid.

Please make sure to provide valid database credentials for the database server at `vortex-postgres`.
Failed to prepare server PrismaClientInitializationError: An error occurred while loading instrumentation hook: 
Invalid `prisma.agent.findMany()` invocation:


Authentication failed against database server at `vortex-postgres`, the provided database credentials for `1234` are not valid.

Please make sure to provide valid database credentials for the database server at `vortex-postgres`.
    at si.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:125:7117)
    at si.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:125:6151)
    at si.request (/app/node_modules/@prisma/client/runtime/library.js:125:5859)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:130:10025)
    at async S (/app/.next/server/chunks/7613.js:40:24659)
    at async Module.v (/app/.next/server/chunks/7613.js:40:21178)
    at async Module.i (/app/.next/server/instrumentation.js:1:196)
    at async NextNodeServer.prepareImpl (/app/node_modules/next/dist/server/next-server.js:437:17) {
  clientVersion: '5.7.1',
  errorCode: undefined
}
PrismaClientInitializationError: An error occurred while loading instrumentation hook: 
Invalid `prisma.agent.findMany()` invocation:


Authentication failed against database server at `vortex-postgres`, the provided database credentials for `1234` are not valid.

Please make sure to provide valid database credentials for the database server at `vortex-postgres`.
    at si.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:125:7117)
    at si.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:125:6151)
    at si.request (/app/node_modules/@prisma/client/runtime/library.js:125:5859)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:130:10025)
    at async S (/app/.next/server/chunks/7613.js:40:24659)
    at async Module.v (/app/.next/server/chunks/7613.js:40:21178)
    at async Module.i (/app/.next/server/instrumentation.js:1:196)
    at async NextNodeServer.prepareImpl (/app/node_modules/next/dist/server/next-server.js:437:17) {
  clientVersion: '5.7.1',
  errorCode: undefined
}
PrismaClientInitializationError: An error occurred while loading instrumentation hook: 
Invalid `prisma.agent.findMany()` invocation:


Authentication failed against database server at `vortex-postgres`, the provided database credentials for `1234` are not valid.

Please make sure to provide valid database credentials for the database server at `vortex-postgres`.
    at si.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:125:7117)
    at si.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:125:6151)
    at si.request (/app/node_modules/@prisma/client/runtime/library.js:125:5859)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:130:10025)
    at async S (/app/.next/server/chunks/7613.js:40:24659)
    at async Module.v (/app/.next/server/chunks/7613.js:40:21178)
    at async Module.i (/app/.next/server/instrumentation.js:1:196)
    at async NextNodeServer.prepareImpl (/app/node_modules/next/dist/server/next-server.js:437:17) {
  clientVersion: '5.7.1',
  errorCode: undefined
}
```

这是`.env`
```
# Prisma
# https://www.prisma.io/docs/reference/database-reference/connection-urls#env
# postgresql://USER:PASSWORD@HOST:PORT/DATABASE
DATABASE_URL="postgresql://1234:123456@vortex-postgres:5432/vortex"
# If you use docker-compose, you should use the following configuration
POSTGRES_USER="1234"
POSTGRES_PASSWORD="123456"
POSTGRES_DB="vortex"
```

**Comment by jarvis2f** [comment]
数据库连不上
